---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/nasashit/nasashit.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/218941/articles/280589/master/file/figures/nasashit/nasashit.xlsx"
