---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/7a584589024cc95c6966edf84a1e6e1aa2d8980c/7a584589024cc95c6966edf84a1e6e1aa2d8980c.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/218941/articles/280589/master/folder/figures/7a584589024cc95c6966edf84a1e6e1aa2d8980c"
    url: "/users/218941/articles/280589/master/file/figures/7a584589024cc95c6966edf84a1e6e1aa2d8980c/7a584589024cc95c6966edf84a1e6e1aa2d8980c.png"
